# Generated by Django 4.1.3 on 2022-11-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=200)),
                ('class_number', models.CharField(choices=[(7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], max_length=50)),
                ('class_index', models.IntegerField()),
            ],
        ),
    ]
