# Generated by Django 4.1.3 on 2022-11-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_index',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_number',
            field=models.IntegerField(choices=[(7, 7), (8, 8), (9, 9), (10, 10), (11, 11)]),
        ),
    ]
