# Generated by Django 4.1.4 on 2023-01-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_author_justbook_parallels_piece_student_textbook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='relevant',
            field=models.SmallIntegerField(blank=True, choices=[(7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], null=True),
        ),
    ]
