# Generated by Django 4.1.4 on 2023-02-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_textbook_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='class_number',
            field=models.CharField(max_length=10, verbose_name='В каком классе выдаются'),
        ),
    ]
