# Generated by Django 4.1.3 on 2022-11-20 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_class_index_alter_student_class_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_take', models.DateTimeField(auto_now_add=True)),
                ('id1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.student')),
                ('id2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.book')),
            ],
        ),
    ]
