# Generated by Django 4.1.4 on 2022-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('class_number', models.IntegerField(choices=[(7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], verbose_name='В каком классе выдаются')),
                ('author', models.ManyToManyField(related_name='author', to='api.author')),
            ],
        ),
        migrations.RemoveField(
            model_name='journal',
            name='id1',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='id2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='FIO',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_index',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_number',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='surname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Journal',
        ),
        migrations.AddField(
            model_name='student',
            name='text_books',
            field=models.ManyToManyField(to='api.textbook'),
        ),
    ]
