# Generated by Django 4.1.4 on 2023-02-09 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_textbook_class_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='relevant',
        ),
    ]
