# Generated by Django 4.1.4 on 2022-12-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_author_textbook_remove_journal_id1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbook',
            old_name='author',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='patronymic',
            field=models.CharField(default='', max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='JustBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.ManyToManyField(related_name='just_author', to='api.author')),
                ('pieces', models.ManyToManyField(related_name='piece', to='api.piece')),
            ],
        ),
    ]
