# Generated by Django 4.1.4 on 2023-02-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_textbook_relevant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
