# Generated by Django 4.1.4 on 2022-12-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_author_textbook_authors_alter_student_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='justbook',
            options={'verbose_name': 'Сборник', 'verbose_name_plural': 'Сборники'},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
        migrations.AlterModelOptions(
            name='textbook',
            options={'verbose_name': 'Учебник', 'verbose_name_plural': 'Учебники'},
        ),
        migrations.AddField(
            model_name='student',
            name='class_index',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='class_number',
            field=models.PositiveSmallIntegerField(choices=[(7, 7), (8, 8), (9, 9), (10, 10), (11, 11)], default=11),
            preserve_default=False,
        ),
    ]
