# Generated by Django 4.1.4 on 2023-02-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_textbook_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justbook',
            name='pieces',
        ),
        migrations.AddField(
            model_name='justbook',
            name='description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Piece',
        ),
    ]
