# Generated by Django 4.1.4 on 2023-02-12 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_justbook_pieces_justbook_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_take', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.textbook')),
            ],
        ),
    ]
