# Generated by Django 4.1.4 on 2023-02-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_takedates'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='take_dates',
            field=models.ManyToManyField(default=None, to='api.takedates'),
        ),
    ]
