# Generated by Django 4.1.4 on 2023-02-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_student_take_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='justbook',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
