# Generated by Django 4.1.4 on 2023-01-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_textbook_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='text_books',
            field=models.ManyToManyField(blank=True, default=None, to='api.textbook'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='authors',
            field=models.ManyToManyField(related_name='text_books', to='api.author'),
        ),
    ]
