# Generated by Django 4.1.4 on 2023-02-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_justbook_description'),
        ('api', '0011_libraryworker_alter_justbook_description'),
    ]

    operations = [
    ]
