# Generated by Django 4.1.4 on 2023-01-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_student_name_alter_student_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='just_books',
            field=models.ManyToManyField(blank=True, default=None, to='api.justbook'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='authors',
            field=models.ManyToManyField(to='api.author'),
        ),
    ]
