# Generated by Django 4.1.4 on 2023-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_student_just_books_alter_textbook_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justbook',
            name='authors',
            field=models.ManyToManyField(to='api.author'),
        ),
        migrations.AlterField(
            model_name='justbook',
            name='pieces',
            field=models.ManyToManyField(to='api.piece'),
        ),
    ]
